  CREATE TABLE CITIES(	
	"ID" 				NUMBER(8,0) NOT NULL ENABLE, 
	"CITY_CO" 			VARCHAR2(10 BYTE), 
	"DESCRIPTION" 		VARCHAR2(80 BYTE), 
	"MUNICIPALITY_ID" 	NUMBER(8,0), 
	"POSTAL_CO" 		VARCHAR2(10 BYTE), 
	"TELEPHONE_CO" 		VARCHAR2(3 BYTE), 
	"SLUG" 				VARCHAR2(60 BYTE), 
	"UUID" 				VARCHAR2(60 BYTE), 
	"USER_ID" 			NUMBER(8,0), 
	"CREATED_AT" 		DATE DEFAULT sysdate, 
	"UPDATED_AT" 		DATE DEFAULT sysdate, 
	"NU_GPS_LAT" 		NUMBER(8,4), 
	"NU_GPS_LON" 		NUMBER(8,4)
);	