CREATE TABLESPACE TS_IGTP_DAT
DATAFILE 'C:\app\oracle\xe21c\oradata\XE\igtp_data.dbf' SIZE 200M;
--
CREATE TABLESPACE TS_IGTP_IDX
DATAFILE 'C:\app\oracle\xe21c\oradata\XE\igtp_index.dbf' SIZE 200M;
--
CREATE TEMPORARY TABLESPACE IGTP_TEMP TEMPFILE 
  'C:\APP\ORACLE\XE21C\ORADATA\XE\igtp_temp.dbf' SIZE 248512512
  AUTOEXTEND ON NEXT 655360 MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1048576;
--
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
--
-- USER SQL
CREATE USER "IGTP" IDENTIFIED BY "IGTP"  
DEFAULT TABLESPACE "IGTP_DATA"
TEMPORARY TABLESPACE "IGTP_TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO "IGTP" ;

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "IGTP" ;
GRANT CREATE TRIGGER TO "IGTP" ;
GRANT CREATE ANY PROCEDURE TO "IGTP" ;
GRANT CREATE ANY DIRECTORY TO "IGTP" ;
GRANT CREATE ANY INDEX TO "IGTP" ;
GRANT CREATE VIEW TO "IGTP" ;
GRANT CREATE SESSION TO "IGTP" ;
GRANT CREATE TABLE TO "IGTP" ;
GRANT CREATE TYPE TO "IGTP" ;
GRANT CREATE PUBLIC SYNONYM TO "IGTP" ;
GRANT CREATE ANY SYNONYM TO "IGTP" ;
GRANT CREATE SYNONYM TO "IGTP" ;
GRANT CREATE SEQUENCE TO "IGTP" ;
GRANT CREATE ANY VIEW TO "IGTP" ;
GRANT DROP PUBLIC SYNONYM TO "IGTP" ;
GRANT CREATE ANY MATERIALIZED VIEW TO "IGTP" ;
GRANT CREATE ANY TRIGGER TO "IGTP" ;
GRANT CREATE ANY TABLE TO "IGTP" ;
GRANT CREATE ANY TYPE TO "IGTP" ;
