--------------------------------------------------------
--  Constraints for Table TRANSFERS
--------------------------------------------------------

  ALTER TABLE "IGTP"."TRANSFERS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IGTP"."TRANSFERS" ADD CONSTRAINT "TRANSFERS_PK" PRIMARY KEY ("ID")
  USING INDEX "IGTP"."TRANSFERS_PK"  ENABLE;
  ALTER TABLE "IGTP"."TRANSFERS" ADD CONSTRAINT "TRANSFER_K_STATUS_CHK" CHECK ( k_status IN ('PLANNED','EXECUTING','TRANSFERRED','COMMIT','ELIMINATED') ) ENABLE;
  ALTER TABLE "IGTP"."TRANSFERS" ADD CONSTRAINT "TRANSFER_K_PROCESS_CHK" CHECK ( k_process IN ('LOGISTY','PAYROLE','ARCHIVING') ) ENABLE;
  ALTER TABLE "IGTP"."TRANSFERS" ADD CONSTRAINT "TRANSFER_K_REGIMEN_CHK" CHECK ( k_regimen IN ('FREIGHT','WEIGHT','DISTANCE','AMOUNT-MANIFEST') ) ENABLE;
