--------------------------------------------------------
--  Constraints for Table TYPE_FREIGHTS
--------------------------------------------------------

  ALTER TABLE "IGTP"."TYPE_FREIGHTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IGTP"."TYPE_FREIGHTS" ADD CONSTRAINT "TYPE_FREIGHTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_DAT"  ENABLE;
  ALTER TABLE "IGTP"."TYPE_FREIGHTS" ADD CONSTRAINT "TYPE_FREIGHTS_UK_01" UNIQUE ("TYPE_FREIGHT_CO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_DAT"  ENABLE;
