--------------------------------------------------------
--  DDL for Table CONFIGURATIONS
--------------------------------------------------------

CREATE TABLE "IGTP"."CONFIGURATIONS" 
(	
	"ID" 							NUMBER(8,0), 
	"LOCAL_CURRENCY_CO" 			VARCHAR2(3 BYTE), 
	"FOREIGN_CURRENCY_CO" 			VARCHAR2(3 BYTE), 
	"LAST_FOREIGN_CURRENCY_Q_VALUE" NUMBER(10,2), 
	"LAST_FOREIGN_CURRENCY_Q_DATE" 	DATE, 
	"COUNTRY_CO" 					VARCHAR2(10 BYTE), 
	"COMPANY_DESCRIPTION" 			VARCHAR2(80 BYTE), 
	"COMPANY_ADDRESS" 				VARCHAR2(250 BYTE), 
	"COMPANY_TELEPHONE_CO" 			VARCHAR2(50 BYTE), 
	"COMPANY_FAX_CO" 				VARCHAR2(50 BYTE), 
	"COMPANY_EMAIL" 				VARCHAR2(60 BYTE), 
	"COMPANY_FISCAL_DOCUMENT_CO" 	VARCHAR2(60 BYTE), 
	"COMPANY_LOGO" 					VARCHAR2(250 BYTE), 
	"DAYS_PER_YEAR" 				NUMBER(3,0) DEFAULT '360', 
	"WEEKS_PER_YEAR" 				NUMBER(2,0) DEFAULT '52', 
	"MONTHS_PER_YEAR" 				NUMBER(2,0) DEFAULT '12', 
	"DAYS_PER_MONTH" 				NUMBER(2,0) DEFAULT '30', 
	"DAYS_PER_WEEK" 				NUMBER(2,0) DEFAULT '7', 
	"HOURS_PER_DAY" 				NUMBER(2,0) DEFAULT '24', 
	"CREATED_AT" 					DATE DEFAULT sysdate, 
	"UPDATED_AT" 					DATE DEFAULT sysdate
) 
SEGMENT CREATION IMMEDIATE 
PCTFREE 10 
PCTUSED 0 
INITRANS 1 
MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(
	INITIAL 65536 
	NEXT 1048576 
	MINEXTENTS 1 
	MAXEXTENTS 2147483645
	PCTINCREASE 0 
	FREELISTS 1 
	FREELIST GROUPS 1
	BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
)
TABLESPACE "TS_IGTP_DAT" ;

COMMENT ON TABLE "IGTP"."CONFIGURATIONS"  IS 'Tabla de configuracion principal de la empresa';

COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."LOCAL_CURRENCY_CO" IS 'Codigo de moneda local';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."FOREIGN_CURRENCY_CO" IS 'Codigo de moneda foranea';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."LAST_FOREIGN_CURRENCY_Q_VALUE" IS 'Ultimo valor de cambio de la moneda foranea';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."LAST_FOREIGN_CURRENCY_Q_DATE" IS 'Ultima fecha de actualizacion del valor de moneda foranea';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."COUNTRY_CO" IS 'Codigo de Pais local';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."COMPANY_DESCRIPTION" IS 'Descripcion de la empresa';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."COMPANY_TELEPHONE_CO" IS 'Codigo telefonico';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."COMPANY_FAX_CO" IS 'Codigo fax';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."COMPANY_EMAIL" IS 'Email principal de la empresa';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."COMPANY_FISCAL_DOCUMENT_CO" IS 'Numero de Identificacion Fiscal';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."COMPANY_LOGO" IS 'direccion URL de la imagen del logo de la empresa';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."DAYS_PER_YEAR" IS 'Dias por anhio';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."WEEKS_PER_YEAR" IS 'Semanas por anhio';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."MONTHS_PER_YEAR" IS 'Meses por anhio';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."DAYS_PER_MONTH" IS 'Dias por Mes';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."DAYS_PER_WEEK" IS 'Dias por Semana';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."HOURS_PER_DAY" IS 'Horas por dias';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."CREATED_AT" IS 'Fecha de creacion';
COMMENT ON COLUMN "IGTP"."CONFIGURATIONS"."UPDATED_AT" IS 'Fecha de actualizacion';