--------------------------------------------------------
--  DDL for Table COUNTRIES
--------------------------------------------------------

  CREATE TABLE "IGTP"."COUNTRIES" 
   (	"ID" NUMBER(8,0), 
	"COUNTRY_CO" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(80 BYTE), 
	"PATH_IMAGE" VARCHAR2(255 BYTE), 
	"TELEPHONE_CO" VARCHAR2(3 BYTE), 
	"USER_ID" NUMBER(8,0), 
	"SLUG" VARCHAR2(60 BYTE), 
	"UUID" VARCHAR2(60 BYTE), 
	"CREATED_AT" DATE DEFAULT sysdate, 
	"UPDATED_AT" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_DAT" ;

   COMMENT ON COLUMN "IGTP"."COUNTRIES"."ID" IS 'IDENTIFICADOR';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."COUNTRY_CO" IS 'CODIGO UNICO DEL PAIS';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."DESCRIPTION" IS 'DESCRIPCION DEL PAIS O NOMBRE';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."PATH_IMAGE" IS 'RUTA DE IMAGEN DEL PAIS COMO BANDERA';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."TELEPHONE_CO" IS 'CODIGO DE DISCADO';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."USER_ID" IS 'IDENTIFICADOR DEL USUARIO QUE ACTUALIZA EL REGISTRO';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."SLUG" IS 'SLUG DESCRIPTIVO';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."UUID" IS 'IDENTIFICADOR UNICO UNIVERSAL';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."CREATED_AT" IS 'FECHA DE CREACION DEL REGISTRO';
   COMMENT ON COLUMN "IGTP"."COUNTRIES"."UPDATED_AT" IS 'FECHA DE ACTUALIZACION DEL REGISTRO';
   COMMENT ON TABLE "IGTP"."COUNTRIES"  IS 'PAISES';
