--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

CREATE TABLE "IGTP"."CUSTOMERS" 
(	
	"ID" 					NUMBER(8,0) DEFAULT IGTP.CUSTOMERS_SEQ.NEXTVAL, 
	"CUSTOMER_CO" 			VARCHAR2(10 BYTE), 
	"DESCRIPTION" 			VARCHAR2(80 BYTE), 
	"K_TYPE_CUSTOMER" 		CHAR(1 BYTE) DEFAULT 'F', 
	"LOCATION_ID" 			NUMBER(8,0), 
	"ADDRESS" 				VARCHAR2(250 BYTE), 
	"TELEPHONE_CO" 			VARCHAR2(50 BYTE), 
	"FAX_CO" 				VARCHAR2(50 BYTE), 
	"EMAIL" 				VARCHAR2(60 BYTE), 
	"FISCAL_DOCUMENT_CO" 	VARCHAR2(20 BYTE), 
	"K_CATEGORY_CO" 		CHAR(1 BYTE) DEFAULT 'C', 
	"K_SECTOR" 				VARCHAR2(30 BYTE), 
	"NAME_CONTACT" 			VARCHAR2(20 BYTE), 
	"TELEPHONE_CONTACT" 	VARCHAR2(20 BYTE), 
	"EMAIL_CONTACT" 		VARCHAR2(60 BYTE), 
	"SLUG" 					VARCHAR2(60 BYTE), 
	"UUID" 					VARCHAR2(60 BYTE), 
	"K_MCA_INH"				CHAR(01) DEFAULT 'N',
	"USER_ID" 				NUMBER(8,0), 
	"CREATED_AT" 			DATE DEFAULT sysdate, 
	"UPDATED_AT" 			DATE DEFAULT sysdate
) 
SEGMENT CREATION IMMEDIATE 
  	PCTFREE 10 
	PCTUSED 0 
	INITRANS 1 
	MAXTRANS 255 
 	NOCOMPRESS LOGGING
  	STORAGE(
		INITIAL 65536 
		NEXT 1048576 
		MINEXTENTS 1 
		MAXEXTENTS 2147483645
  		PCTINCREASE 0 
		FREELISTS 1 
		FREELIST GROUPS 1
  		BUFFER_POOL DEFAULT 
		FLASH_CACHE DEFAULT 
		CELL_FLASH_CACHE DEFAULT
	)
  	TABLESPACE "TS_IGTP_DAT" ;
/
COMMENT ON TABLE "IGTP"."CUSTOMERS"  IS 'Clientes'

COMMENT ON COLUMN "IGTP"."CUSTOMERS.K_TYPE_CUSTOMER" IS "Tipo de Cliente, F->Factory, D->Distribution, M->Market" 