--------------------------------------------------------
--  DDL for Table FREIGHTS
--------------------------------------------------------

CREATE TABLE "IGTP"."FREIGHTS" 
(	
	"ID" 				NUMBER(20,0) DEFAULT IGTP.FREIGHTS_SEQ.NEXTVAL, 
	"FREIGHT_CO" 		VARCHAR2(20 BYTE), 
	"CUSTOMER_ID" 		NUMBER(20,0), 
	"ROUTE_ID" 			NUMBER(20,0), 
	"TYPE_CARGO_ID" 	NUMBER(20,0), 
	"TYPE_VEHICLE_ID" 	NUMBER(20,0), 
	"TYPE_FREIGHT_ID" 	NUMBER(20,0),
	"K_REGIMEN" 		VARCHAR2(20 BYTE), 
	"UPLOAD_AT" 		DATE, 
	"START_AT" 			DATE, 
	"FINISH_AT" 		DATE, 
	"NOTES" 			VARCHAR2(80 BYTE), 
	"K_STATUS" 			VARCHAR2(20 BYTE), 
	"K_PROCESS" 		VARCHAR2(20 BYTE), 
	"USER_ID" 			NUMBER(20,0), 
	"CREATED_AT" 		DATE DEFAULT sysdate, 
	"UPDATED_AT" 		DATE DEFAULT sysdate
) 
SEGMENT CREATION IMMEDIATE 
	PCTFREE 10 
	PCTUSED 0 
	INITRANS 1 
	MAXTRANS 255 
	NOCOMPRESS LOGGING
  	STORAGE(
		INITIAL 65536 
		NEXT 1048576 
		MINEXTENTS 1 
		MAXEXTENTS 2147483645
  		PCTINCREASE 0 
		FREELISTS 1 
		FREELIST GROUPS 1
  		BUFFER_POOL DEFAULT 
		FLASH_CACHE DEFAULT 
		CELL_FLASH_CACHE DEFAULT
	)
  	TABLESPACE "TS_IGTP_DAT" ;
--
COMMENT ON TABLE "IGTP"."FREIGHTS"  IS 'Viajes o Declaracion de Fletes';
COMMENT ON COLUMN "IGTP"."FREIGHTS"."FREIGHT_CO" 	IS 'Codigo externo del flete';
COMMENT ON COLUMN "IGTP"."FREIGHTS"."ROUTE_ID" 		IS 'Identificador de la Ruta';
