--------------------------------------------------------
--  DDL for Table TRANSFER_SHOPS
--------------------------------------------------------

CREATE TABLE "IGTP"."TRANSFER_SHOPS" 
(	
   "ID"                 NUMBER(8,0) DEFAULT IGTP.TRANSFER_SHOPS_SEQ.NEXTVAL, 
	"TRANSFER_ID"        NUMBER(8,0), 
	"SHOP_ID"            NUMBER(8,0), 
	"K_REPARTO"          CHAR(1 BYTE) DEFAULT 'N', 
	"DOCUMENT_REF"       VARCHAR2(50 BYTE), 
	"TYPE_DOCUMENT_ID"   NUMBER(8,0), 
	"IMP_VALUE"          NUMBER, 
	"CURRENCY_CO"        VARCHAR2(3 BYTE), 
	"USER_ID"            NUMBER(8,0), 
	"CREATE_AT"          DATE DEFAULT NULL, 
	"UPDATE_AT"          DATE DEFAULT NULL, 
	"TYPE_JSON"          VARCHAR2(20 BYTE), 
	"PAYLOAD_JSON"       CLOB, 
	"DOCUMENT_PARENT_ID" NUMBER(8,0)
) 
SEGMENT CREATION IMMEDIATE 
   PCTFREE 10 
   PCTUSED 0 
   INITRANS 1 
   MAXTRANS 255 
   NOCOMPRESS LOGGING
   STORAGE(
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS 2147483645
      PCTINCREASE 0 
      FREELISTS 1 
      FREELIST GROUPS 1
      BUFFER_POOL DEFAULT 
      FLASH_CACHE DEFAULT 
      CELL_FLASH_CACHE DEFAULT
   )
   TABLESPACE "TS_IGTP_DAT" 
      LOB ("PAYLOAD_JSON") STORE AS SECUREFILE (
         TABLESPACE "TS_IGTP_DAT" ENABLE STORAGE IN ROW 4000 
         CHUNK 8192
         NOCACHE LOGGING  
         NOCOMPRESS  
         KEEP_DUPLICATES 
      STORAGE(
         INITIAL 262144 
         NEXT 1048576 
         MINEXTENTS 1 
         MAXEXTENTS 2147483645
         PCTINCREASE 0
         BUFFER_POOL DEFAULT 
         FLASH_CACHE DEFAULT 
         CELL_FLASH_CACHE DEFAULT
      )
   );

COMMENT ON TABLE "IGTP"."TRANSFER_SHOPS"  IS 'Documentos asociados a tiendas';
