--------------------------------------------------------
--  DDL for Table SUBSIDIARIES
--------------------------------------------------------

CREATE TABLE "IGTP"."SUBSIDIARIES"(	
   "ID"              NUMBER(8,0) GENERATED BY DEFAULT AS IDENTITY 
                                    MINVALUE 1 
                                    MAXVALUE 9999999999999999999999999999 
                                    INCREMENT BY 1 
                                    START WITH 1 
                                    CACHE 20 
                                    NOORDER NOCYCLE NOKEEP NOSCALE ,
   "SUBSIDIARY_CO"   VARCHAR2(10 BYTE), 
   "CUSTOMER_ID"     NUMBER(8,0), 
   "SHOP_ID"         NUMBER(8,0), 
   "USER_ID"         NUMBER(8,0), 
   "UUID"            VARCHAR2(60 BYTE), 
   "SLUG"            VARCHAR2(60 BYTE), 
   "CREATED_AT"      DATE DEFAULT sysdate, 
   "UPDATED_AT"      DATE DEFAULT sysdate
) 
SEGMENT CREATION IMMEDIATE 
   PCTFREE 10 
   PCTUSED 0 
   INITRANS 1 
   MAXTRANS 255 
   NOCOMPRESS LOGGING
   STORAGE(
      INITIAL 65536 
      NEXT 1048576 
      MINEXTENTS 1 
      MAXEXTENTS 2147483645
      PCTINCREASE 0 
      FREELISTS 1 FREELIST GROUPS 1
      BUFFER_POOL DEFAULT 
      FLASH_CACHE DEFAULT 
      CELL_FLASH_CACHE DEFAULT
   )
   TABLESPACE "TS_IGTP_DAT" ;

COMMENT ON TABLE "IGTP"."SUBSIDIARIES"  IS 'Subsidiarias de Clientes en ciudad';
COMMENT ON COLUMN "IGTP"."SUBSIDIARIES"."ID" IS 'Identificador de la subsidiaria';
COMMENT ON COLUMN "IGTP"."SUBSIDIARIES"."SUBSIDIARY_CO" IS 'Codigo de la subsidiaria';
COMMENT ON COLUMN "IGTP"."SUBSIDIARIES"."SHOP_ID" IS 'Identificador de la tienda';