--------------------------------------------------------
--  DDL for Table table_type_cargos
--------------------------------------------------------
CREATE TABLE "IGTP"."TYPE_CARGOS" (	
   "ID"             NUMBER(20,0) GENERATED BY DEFAULT AS IDENTITY 
                              MINVALUE 1 
                              MAXVALUE 9999999999999999999999999999 
                              INCREMENT BY 1 
                              START WITH 1 
                              CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
   "TYPE_CARGO_CO"  VARCHAR2(10 BYTE), 
   "DESCRIPTION"    VARCHAR2(80 BYTE), 
   "K_ACTIVE"       CHAR(1 BYTE) DEFAULT 'Y', 
   "USER_ID"        NUMBER(20,0), 
   "CREATED_AT"     DATE DEFAULT sysdate, 
   "UPDATED_AT"     DATE DEFAULT sysdate
) SEGMENT CREATION IMMEDIATE 
    PCTFREE 10 
    PCTUSED 0 
    INITRANS 1 
    MAXTRANS 255 
    NOCOMPRESS LOGGING
    STORAGE(
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645
        PCTINCREASE 0 
        FREELISTS 1 
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT 
        FLASH_CACHE DEFAULT 
        CELL_FLASH_CACHE DEFAULT
) TABLESPACE "TS_IGTP_DAT" ;
--
COMMENT ON TABLE "IGTP"."TYPE_CARGOS"                   IS 'Tipos de cargos';
--
COMMENT ON COLUMN "IGTP"."TYPE_CARGOS"."ID"             IS 'Identificador correlativo unico';
COMMENT ON COLUMN "IGTP"."TYPE_CARGO_CO"."ID"           IS 'Codigo externo del tipo de carga';
