--------------------------------------------------------
--  DDL for Table table_freights
--------------------------------------------------------  
  CREATE TABLE "IGTP"."FREIGHTS" (	
	"ID" 			    NUMBER(20,0) GENERATED BY DEFAULT AS IDENTITY 
								MINVALUE 1 
								MAXVALUE 9999999999999999999999999999 
								INCREMENT BY 1 
								START WITH 1 
								CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
    "FREIGHTS_CO"       VARCHAR2(20),
	"CUSTOMER_ID" 	    NUMBER(20,0), 
	"ROUTE_ID" 	        NUMBER(20,0), 
    "TYPE_CARGO_ID"     NUMBER(20,0), 
    "TYPE_VEHICLE_ID"   NUMBER(20,0), 
    "K_REGIMEN"         VARCHAR2(20) DEFAULT 'FREIGHT', 
    "UPLOAD_AT" 	    DATE, 
    "START_AT" 	        DATE,  
    "FINISH_AT" 	    DATE,
    "NOTES" 	        VARCHAR2(80),  
    "K_STATUS"          VARCHAR2(20) DEFAULT 'PLANNED', 
    "K_PROCESS"         VARCHAR2(20) DEFAULT 'LOGISTY',, 
	"USER_ID"           NUMBER(20,0), 
	"CREATED_AT"        DATE DEFAULT sysdate, 
	"UPDATED_AT"        DATE DEFAULT sysdate
) SEGMENT CREATION DEFERRED 
    PCTFREE 10 
    PCTUSED 0 
    INITRANS 1 
    MAXTRANS 255 
    NOCOMPRESS LOGGING
    STORAGE( 
        INITIAL 65536 
        MINEXTENTS 1 
        MAXEXTENTS 2147483645
        PCTINCREASE 0
        BUFFER_POOL DEFAULT 
        FLASH_CACHE DEFAULT 
        CELL_FLASH_CACHE DEFAULT
) TABLESPACE "TS_IGTP_DAT" ;