--------------------------------------------------------
--  DDL for Table TRANSFER_SHOPS
--------------------------------------------------------

  CREATE TABLE "IGTP"."TRANSFER_SHOPS" 
   (	"ID" NUMBER(8,0), 
	"TRANSFER_ID" NUMBER(8,0), 
	"SHOP_ID" NUMBER(8,0), 
	"K_REPARTO" CHAR(1 BYTE) DEFAULT 'N', 
	"DOCUMENT_REF" VARCHAR2(50 BYTE), 
	"TYPE_DOCUMENT_ID" NUMBER(8,0), 
	"IMP_VALUE" NUMBER, 
	"CURRENCY_CO" VARCHAR2(3 BYTE), 
	"USER_ID" NUMBER(8,0), 
	"CREATE_AT" DATE DEFAULT NULL, 
	"UPDATE_AT" DATE DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_DAT" ;

   COMMENT ON TABLE "IGTP"."TRANSFER_SHOPS"  IS 'Documentos asociados a tiendas';
