--------------------------------------------------------
--  DDL for Table TRANSFERS
--------------------------------------------------------

CREATE TABLE "IGTP"."TRANSFERS" 
(	
	"ID" 				NUMBER(20,0) DEFAULT IGTP.TRANSFERS_SEQ.NEXTVAL,
	"FREIGHT_ID" 		NUMBER(20,0), 
	"K_ORDER" 			NUMBER(6,0), 
	"SEQUENCE_NUMBER" 	NUMBER(3,0),
	"ROUTE_ID" 			NUMBER(20,0), 
	"K_REGIMEN" 		VARCHAR2(20 BYTE) DEFAULT 'FREIGHT', 
	"K_STATUS" 			VARCHAR2(20 BYTE) DEFAULT 'PLANNED', 
	"K_PROCESS" 		VARCHAR2(20 BYTE) DEFAULT 'LOGISTY', 
	"K_TYPE_TRANSFER" 	VARCHAR2(20 BYTE), 
	"PLANED_AT" 		DATE DEFAULT sysdate, 
	"START_AT" 			DATE DEFAULT sysdate, 
	"END_AT" 			DATE DEFAULT sysdate, 
	"TRUCK_ID" 			NUMBER(20,0), 
	"TRAILER_ID" 		NUMBER(20,0), 
	"MAIN_EMPLOYEE_ID" 	NUMBER(20,0), 
	"AUX_EMPLOYEE_ID" 	NUMBER(20,0), 
	"NOTE"				VARCHAR2(512),
	"USER_ID" 			NUMBER(20,0), 
	"CREATED_AT" 		DATE DEFAULT sysdate, 
	"UPDATED_AT" 		DATE DEFAULT sysdate
) 
SEGMENT CREATION IMMEDIATE 
  	PCTFREE 10 
	PCTUSED 0 
	INITRANS 1 
	MAXTRANS 255 
 	NOCOMPRESS LOGGING
  	STORAGE(
		INITIAL 65536 
		NEXT 1048576 
		MINEXTENTS 1 
		MAXEXTENTS 2147483645
  		PCTINCREASE 0 
		FREELISTS 1 
		FREELIST GROUPS 1
  		BUFFER_POOL DEFAULT 
		FLASH_CACHE DEFAULT 
		CELL_FLASH_CACHE DEFAULT
	)
	TABLESPACE "TS_IGTP_DAT" ;
--
COMMENT ON TABLE "IGTP"."TRANSFERS"  IS 'Transferencias de Cargas en un Viaje';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."ID" IS 'Identificador correlativo unico';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."FREIGHT_ID" IS 'Referencia unica al viaje';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."K_ORDER" IS 'Orden de Ejecucion';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."SEQUENCE_NUMBER" IS 'Secuencia de registro o planeacion';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."ROUTE_ID" IS 'Referencia unica a la ruta de la transferencia';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."K_REGIMEN" IS 'Regimen de carga o transporte';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."K_STATUS" IS 'Estado del Viaje segun los distintos proceso que lo trata';
COMMENT ON COLUMN "IGTP"."TRANSFERS"."K_PROCESS" IS 'Proceso actual de tratamiento del Viaje';















