--------------------------------------------------------
--  DDL for Index COUNTRIES_UK_00
--------------------------------------------------------

CREATE UNIQUE INDEX "IGTP"."PROCESSES_UK_00" 
  ON "IGTP"."PROCESSES" ("PROCESS_CO", "K_EVENT_PROCESS", "SEQUENCE") 
  PCTFREE 10 
  INITRANS 2 
  MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645
    PCTINCREASE 0 
    FREELISTS 1 
    FREELIST GROUPS 1
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
TABLESPACE "TS_IGTP_IDX" ;
