--------------------------------------------------------
--  DDL for Index TRANSFERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "IGTP"."TRANSFERS_PK" ON "IGTP"."TRANSFERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_IDX" ;
