--------------------------------------------------------
--  DDL for Index TYPE_CASHIER_MOVEMENTS_UK_00
--------------------------------------------------------

  CREATE UNIQUE INDEX "IGTP"."TYPE_CASHIER_MOVEMENTS_UK_00" ON "IGTP"."TYPE_CASHIER_MOVEMENTS" ("TYPE_MOVEMENT_CO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_IDX" ;
