--------------------------------------------------------
--  Constraints for Table MUNICIPALITIES
--------------------------------------------------------

ALTER TABLE "IGTP"."MUNICIPALITIES" 
  ADD CONSTRAINT "MUNICIPALITIES_PK" PRIMARY KEY ("ID")
  USING INDEX "IGTP"."MUNICIPALITIES_PK"  ENABLE;

ALTER TABLE "IGTP"."MUNICIPALITIES" 
  ADD CONSTRAINT "MUNICIPALITIES_UK_00" UNIQUE ("MUNICIPALITY_CO")
  USING INDEX "IGTP"."MUNICIPALITIES_UK_00" ENABLE;