--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

ALTER TABLE "IGTP"."COUNTRIES" 
  ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ID")
  USING INDEX "IGTP"."COUNTRIES_PK"  ENABLE;

ALTER TABLE "IGTP"."COUNTRIES" 
  ADD CONSTRAINT "COUNTRIES_UK_00" UNIQUE ("COUNTRY_CO")
  USING INDEX "IGTP"."COUNTRIES_UK_00" ENABLE;

ALTER TABLE "IGTP"."COUNTRIES" 
  ADD CONSTRAINT "COUNTRIES_UK_01" UNIQUE ("UUID")
  USING INDEX "IGTP"."COUNTRIES_UK_01" ENABLE;
