--------------------------------------------------------
--  Constraints for Table CITIES
--------------------------------------------------------

  ALTER TABLE "IGTP"."CITIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IGTP"."CITIES" ADD CONSTRAINT "CITIES_PK" PRIMARY KEY ("ID")
  USING INDEX "IGTP"."CITIES_PK"  ENABLE;
  ALTER TABLE "IGTP"."CITIES" ADD CONSTRAINT "CITIES_UK_00" UNIQUE ("CITY_CO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_DAT"  ENABLE;
