--------------------------------------------------------
--  Constraints for Table FREIGHTS
--------------------------------------------------------

ALTER TABLE "IGTP"."FREIGHTS" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "IGTP"."FREIGHTS" 
  ADD CONSTRAINT "FREIGHTS_PK" 
  PRIMARY KEY ("ID")
  USING INDEX "IGTP"."FREIGHTS_PK"  ENABLE;

ALTER TABLE "IGTP"."FREIGHTS" 
  ADD CONSTRAINT "K_REGIMEN_CHK" 
  CHECK ( k_regimen IN ('FREIGHT','WEIGHT','DISTANCE','AMOUNT-MANIFEST') ) ENABLE;

ALTER TABLE "IGTP"."FREIGHTS" 
  ADD CONSTRAINT "K_PROCESS_CHK" 
  CHECK ( k_process IN ('LOGISTIC','INVOICING','ARCHIVING') ) ENABLE;

ALTER TABLE "IGTP"."FREIGHTS" 
  ADD CONSTRAINT "K_STATUS_FREIGHTS_CHK" 
  CHECK ( k_status IN ('PLANNED','EXECUTING','COMMIT','ELIMINATED','INCOMPLETE','INVOICED','ARCHIVED') ) ENABLE;

ALTER TABLE "IGTP"."FREIGHTS" 
  ADD CONSTRAINT "FREIGHTS_UK_01" 
  UNIQUE ("FREIGHT_CO")
  USING INDEX "IGTP"."FREIGHTS_UK_01" ENABLE;
