--------------------------------------------------------
--  Constraints for Table FREIGHTS
--------------------------------------------------------

  ALTER TABLE "IGTP"."FREIGHTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "IGTP"."FREIGHTS" ADD CONSTRAINT "FREIGHTS_PK" PRIMARY KEY ("ID")
  USING INDEX "IGTP"."FREIGHTS_PK"  ENABLE;
  ALTER TABLE "IGTP"."FREIGHTS" ADD CONSTRAINT "K_REGIMEN_CHK" CHECK ( k_regimen IN ('FREIGHT','WEIGHT','DISTANCE','AMOUNT-MANIFEST') ) ENABLE;
  ALTER TABLE "IGTP"."FREIGHTS" ADD CONSTRAINT "K_PROCESS_CHK" CHECK ( k_process IN ('LOGISTIC','INVOICING','ARCHIVING') ) ENABLE;
  ALTER TABLE "IGTP"."FREIGHTS" ADD CONSTRAINT "K_STATUS_FREIGHTS_CHK" CHECK ( k_status IN ('PLANNED','EXECUTING','COMMIT','ELIMINATED','INCOMPLETE','INVOICED','ARCHIVED') ) ENABLE;
  ALTER TABLE "IGTP"."FREIGHTS" ADD CONSTRAINT "FREIGHTS_UK_01" UNIQUE ("FREIGHT_CO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_IGTP_DAT"  ENABLE;
