--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

ALTER TABLE "IGTP"."FREIGHT_CFG" 
    ADD	CONSTRAINT "K_REGIMEN_CFG_CHK" 
    CHECK ( k_regimen IN ('FREIGHT','WEIGHT','DISTANCE','AMOUNT-MANIFEST') ) ENABLE;

ALTER TABLE "IGTP"."FREIGHT_CFG" 
    ADD	CONSTRAINT "FREIGHT_CFG_CUSTOMER_FK" FOREIGN KEY ("CUSTOMER_ID")
	REFERENCES "IGTP"."CUSTOMERS" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGHT_CFG" 
    ADD	CONSTRAINT "FREIGHT_CFG_ROUTE_FK" FOREIGN KEY ("ROUTE_ID")
	REFERENCES "IGTP"."ROUTES" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGHT_CFG" 
    ADD	CONSTRAINT "FREIGHT_CFG_TYPE_CARGO_FK" FOREIGN KEY ("TYPE_CARGO_ID")
	REFERENCES "IGTP"."TYPE_CARGOS" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGHT_CFG" 
    ADD	CONSTRAINT "FREIGHT_CFG_TYPE_VEHICLE_FK" FOREIGN KEY ("TYPE_VEHICLE_ID")
	REFERENCES "IGTP"."TYPE_VEHICLES" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGHT_CFG" 
    ADD	CONSTRAINT "FREIGHT_CFG_TYPE_FREIGHT_FK" FOREIGN KEY ("TYPE_FREIGHT_ID")
	REFERENCES "IGTP"."TYPE_FREIGHTS" ("ID") ENABLE;