CREATE TABLE "IGTP"."J_PURCHASEORDER" 
   (	"ID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"DATE_LOADED" DATE, 
	"PO_DOCUMENT" CLOB, 
	 CONSTRAINT "ENSURE_JSON" CHECK (po_document IS JSON) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "IGTP_DATA" 
 LOB ("PO_DOCUMENT") STORE AS SECUREFILE (
  TABLESPACE "IGTP_DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;