REM INSERTING into IGTP.TYPE_DOCUMENTS
SET DEFINE OFF;
Insert into IGTP.TYPE_DOCUMENTS (ID,TYPE_DOCUMENT_CO,DESCRIPTION,USER_ID,CREATED_AT,UPDATED_AT) values ('1','FAC','FACTURA','6',to_date('10/03/23','DD/MM/RR'),to_date('10/03/23','DD/MM/RR'));
Insert into IGTP.TYPE_DOCUMENTS (ID,TYPE_DOCUMENT_CO,DESCRIPTION,USER_ID,CREATED_AT,UPDATED_AT) values ('2','RGA','RELACION DE GASTOS','6',to_date('10/03/23','DD/MM/RR'),to_date('10/03/23','DD/MM/RR'));
Insert into IGTP.TYPE_DOCUMENTS (ID,TYPE_DOCUMENT_CO,DESCRIPTION,USER_ID,CREATED_AT,UPDATED_AT) values ('3','NDE','NOTA DE ENTREGA','6',to_date('10/03/23','DD/MM/RR'),to_date('10/03/23','DD/MM/RR'));
Insert into IGTP.TYPE_DOCUMENTS (ID,TYPE_DOCUMENT_CO,DESCRIPTION,USER_ID,CREATED_AT,UPDATED_AT) values ('4','PAJ','PEAJE','6',to_date('10/03/23','DD/MM/RR'),to_date('10/03/23','DD/MM/RR'));
Insert into IGTP.TYPE_DOCUMENTS (ID,TYPE_DOCUMENT_CO,DESCRIPTION,USER_ID,CREATED_AT,UPDATED_AT) values ('5','CAL','CALETA','6',to_date('10/03/23','DD/MM/RR'),to_date('10/03/23','DD/MM/RR'));
