REM INSERTING into IGTP.TYPE_CARGOS
SET DEFINE OFF;
Insert into IGTP.TYPE_CARGOS (ID,TYPE_CARGO_CO,DESCRIPTION,K_ACTIVE,USER_ID,CREATED_AT,UPDATED_AT) values ('1','REF','CARGA REFRIGERADA','Y','1',to_date('19/04/23','DD/MM/RR'),to_date('19/04/23','DD/MM/RR'));
Insert into IGTP.TYPE_CARGOS (ID,TYPE_CARGO_CO,DESCRIPTION,K_ACTIVE,USER_ID,CREATED_AT,UPDATED_AT) values ('2','SEC','CARGA SECA','Y','1',to_date('19/04/23','DD/MM/RR'),to_date('19/04/23','DD/MM/RR'));
Insert into IGTP.TYPE_CARGOS (ID,TYPE_CARGO_CO,DESCRIPTION,K_ACTIVE,USER_ID,CREATED_AT,UPDATED_AT) values ('3','CPE','CARGA PELIGROSA','Y','1',to_date('19/04/23','DD/MM/RR'),to_date('19/04/23','DD/MM/RR'));
Insert into IGTP.TYPE_CARGOS (ID,TYPE_CARGO_CO,DESCRIPTION,K_ACTIVE,USER_ID,CREATED_AT,UPDATED_AT) values ('4','CDE','CARGA DELICADA','Y','1',to_date('19/04/23','DD/MM/RR'),to_date('19/04/23','DD/MM/RR'));
Insert into IGTP.TYPE_CARGOS (ID,TYPE_CARGO_CO,DESCRIPTION,K_ACTIVE,USER_ID,CREATED_AT,UPDATED_AT) values ('5','CMP','CARGA MAQUINARIA','Y','1',to_date('19/04/23','DD/MM/RR'),to_date('19/04/23','DD/MM/RR'));
