--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "IGTP"."USERS" (	
	"ID" 				NUMBER(8,0) DEFAULT IGTP.USERS_SEQ.NEXTVAL, 
	"USER_CO" 			VARCHAR2(10 BYTE), 
	"NAME" 	    		VARCHAR2(80 BYTE), 
	"EMAIL" 			VARCHAR2(60 BYTE), 
	"EMAIL_VERIFIED_AT" DATE DEFAULT sysdate, 
	"PASSWORD" 			VARCHAR2(255 BYTE), 
	"API_TOKEN" 		VARCHAR2(64 BYTE), 
	"TOKEN_AT" 			DATE DEFAULT sysdate, 
	"UUID" 				VARCHAR2(60 BYTE), 
	"ROL" 				VARCHAR2(50 BYTE), 
	"DEVICE_ID" 		VARCHAR2(50 BYTE), 
	"REMEMBER_TOKEN" 	VARCHAR2(100 BYTE), 
	"K_VALID" 			CHAR(1 BYTE) DEFAULT 'N', 
	"ADDRESS_IP" 		VARCHAR2(60 BYTE), 
	"CREATED_AT" 		DATE DEFAULT sysdate, 
	"UPDATED_AT" 		DATE DEFAULT sysdate
   ) 
   SEGMENT CREATION IMMEDIATE 
  	PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 	NOCOMPRESS LOGGING
  	STORAGE(
		INITIAL 65536 
		NEXT 1048576 
		MINEXTENTS 1 
		MAXEXTENTS 2147483645
  		PCTINCREASE 0 
		FREELISTS 1 
		FREELIST GROUPS 1
  		BUFFER_POOL DEFAULT 
		FLASH_CACHE DEFAULT 
		CELL_FLASH_CACHE DEFAULT
	)
  	TABLESPACE "TS_IGTP_DAT" ;
