--------------------------------------------------------
--  Ref Constraints for Table FREIGTHS
--------------------------------------------------------

ALTER TABLE "IGTP"."FREIGTHS" 
    ADD CONSTRAINT "CUSTOMER_FROM_FREIGHT_FK" 
    FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "IGTP"."CUSTOMERS" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGTHS" 
    ADD CONSTRAINT "ROUTE_TO_FREIGTH_FK" 
    FOREIGN KEY ("ROUTE_ID")
    REFERENCES "IGTP"."ROUTES" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGTHS" 
    ADD CONSTRAINT "TYPE_CARGO_TO_FREIGTH_FK" 
    FOREIGN KEY ("TYPE_CARGO_ID")
    REFERENCES "IGTP"."TYPE_CARGOS" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGTHS" 
    ADD CONSTRAINT "TYPE_VEHICLE_TO_FREIGTH_FK" 
    FOREIGN KEY ("TYPE_VEHICLE_ID")
    REFERENCES "IGTP"."TYPE_VEHICLES" ("ID") ENABLE;

ALTER TABLE "IGTP"."FREIGTHS" 
    ADD CONSTRAINT "TYPE_FREIGHT_TO_FREIGTH_FK" 
    FOREIGN KEY ("TYPE_FREIGHT_ID")
    REFERENCES "IGTP"."TYPE_FREIGHTS" ("ID") ENABLE;