--------------------------------------------------------
--  Ref Constraints for Table FREIGTHS
--------------------------------------------------------

ALTER TABLE "IGTP"."TRANSFERS" 
    ADD CONSTRAINT "FREIGHT_FROM_FREIGHT_FK" 
    FOREIGN KEY ("FREIGHT_ID")
    REFERENCES "IGTP"."FREIGHTS" ("ID") ENABLE;

ALTER TABLE "IGTP"."TRANSFERS" 
    ADD CONSTRAINT "ROUTE_TO_TRANSFER_FK" 
    FOREIGN KEY ("ROUTE_ID")
    REFERENCES "IGTP"."ROUTES" ("ID") ENABLE;

ALTER TABLE "IGTP"."TRANSFERS" 
    ADD CONSTRAINT "TRUCK_TO_TRANSFER_FK" 
    FOREIGN KEY ("TRUCK_ID")
    REFERENCES "IGTP"."TRUCKS" ("ID") ENABLE;

ALTER TABLE "IGTP"."TRANSFERS" 
    ADD CONSTRAINT "TRAILER_TO_TRANSFER_FK" 
    FOREIGN KEY ("TRAILER_ID")
    REFERENCES "IGTP"."TRAILERS" ("ID") ENABLE;

ALTER TABLE "IGTP"."TRANSFERS" 
    ADD CONSTRAINT "EMPLOYEE_TO_TRANSFER_FK" 
    FOREIGN KEY ("MAIN_EMPLOYEE_ID")
    REFERENCES "IGTP"."EMPLOYEES" ("ID") ENABLE;