--------------------------------------------------------
-- Archivo creado  - sábado-junio-17-2023   
--------------------------------------------------------
@C:\proyectos\igtp5\TYPES\T_CSV_LINE.sql
@C:\proyectos\igtp5\TYPES\T_CSV_TAB.sql
@C:\proyectos\igtp5\TYPES\T_DATE_ARRAY.sql
@C:\proyectos\igtp5\TYPES\T_NUM_ARRAY.sql
@C:\proyectos\igtp5\TYPES\T_STR_ARRAY.sql
@C:\proyectos\igtp5\TYPES\TYP_CONFIGURATION.sql
@C:\proyectos\igtp5\SEQUENCES\CITIES_SEQ.sql
@C:\proyectos\igtp5\SEQUENCES\PROVINCES_SEQ.sql
@C:\proyectos\igtp5\SEQUENCES\REGIONS_SEQ.sql
@C:\proyectos\igtp5\TABLES\CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\TABLES\CASHIERS.sql
@C:\proyectos\igtp5\TABLES\CITIES.sql
@C:\proyectos\igtp5\TABLES\CONFIGURATIONS.sql
@C:\proyectos\igtp5\TABLES\COUNTRIES.sql
@C:\proyectos\igtp5\TABLES\CUSTOMERS.sql
@C:\proyectos\igtp5\TABLES\DATABASE_PARAMETERS.sql
@C:\proyectos\igtp5\TABLES\EMPLOYEES.sql
@C:\proyectos\igtp5\TABLES\FREIGHTS.sql
@C:\proyectos\igtp5\TABLES\LOCATION_NEIGHBORS.sql
@C:\proyectos\igtp5\TABLES\LOCATIONS.sql
@C:\proyectos\igtp5\TABLES\MUNICIPALITIES.sql
@C:\proyectos\igtp5\TABLES\PARTNERS.sql
@C:\proyectos\igtp5\TABLES\PROVINCES.sql
@C:\proyectos\igtp5\TABLES\REGIONS.sql
@C:\proyectos\igtp5\TABLES\ROUTE_COSTS.sql
@C:\proyectos\igtp5\TABLES\ROUTE_LOCATIONS.sql
@C:\proyectos\igtp5\TABLES\ROUTES.sql
@C:\proyectos\igtp5\TABLES\SHOPS.sql
@C:\proyectos\igtp5\TABLES\SUBSIDIARIES.sql
@C:\proyectos\igtp5\TABLES\TRAILERS.sql
@C:\proyectos\igtp5\TABLES\TRANSFERS.sql
@C:\proyectos\igtp5\TABLES\TRUCKS.sql
@C:\proyectos\igtp5\TABLES\TYPE_CARGOS.sql
@C:\proyectos\igtp5\TABLES\TYPE_CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\TABLES\TYPE_DOCUMENTS.sql
@C:\proyectos\igtp5\TABLES\TYPE_FREIGHTS.sql
@C:\proyectos\igtp5\TABLES\TYPE_VEHICLES.sql
@C:\proyectos\igtp5\TABLES\UNITS_LOCATED.sql
@C:\proyectos\igtp5\TABLES\USERS.sql
@C:\proyectos\igtp5\VIEWS\V_CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\VIEWS\V_CONFIGURATIONS.sql
@C:\proyectos\igtp5\VIEWS\V_CUSTOMER_SHOPS.sql
@C:\proyectos\igtp5\VIEWS\V_FREIGHTS.sql
@C:\proyectos\igtp5\VIEWS\V_LOCATION_NEIGHBORS.sql
@C:\proyectos\igtp5\VIEWS\V_LOCATION_ROUTE_POSITIONS.sql
@C:\proyectos\igtp5\VIEWS\V_PROVINCES_REGIONS.sql
@C:\proyectos\igtp5\VIEWS\V_ROUTE_LOCATIONS.sql
@C:\proyectos\igtp5\DATA_TABLE\CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\DATA_TABLE\CASHIERS.sql
@C:\proyectos\igtp5\DATA_TABLE\CITIES.sql
@C:\proyectos\igtp5\DATA_TABLE\CONFIGURATIONS.sql
@C:\proyectos\igtp5\DATA_TABLE\COUNTRIES.sql
@C:\proyectos\igtp5\DATA_TABLE\CUSTOMERS.sql
@C:\proyectos\igtp5\DATA_TABLE\DATABASE_PARAMETERS.sql
@C:\proyectos\igtp5\DATA_TABLE\EMPLOYEES.sql
@C:\proyectos\igtp5\DATA_TABLE\FREIGHTS.sql
@C:\proyectos\igtp5\DATA_TABLE\LOCATION_NEIGHBORS.sql
@C:\proyectos\igtp5\DATA_TABLE\LOCATIONS.sql
@C:\proyectos\igtp5\DATA_TABLE\MUNICIPALITIES.sql
@C:\proyectos\igtp5\DATA_TABLE\PARTNERS.sql
@C:\proyectos\igtp5\DATA_TABLE\PROVINCES.sql
@C:\proyectos\igtp5\DATA_TABLE\REGIONS.sql
@C:\proyectos\igtp5\DATA_TABLE\ROUTE_COSTS.sql
@C:\proyectos\igtp5\DATA_TABLE\ROUTE_LOCATIONS.sql
@C:\proyectos\igtp5\DATA_TABLE\ROUTES.sql
@C:\proyectos\igtp5\DATA_TABLE\SHOPS.sql
@C:\proyectos\igtp5\DATA_TABLE\SUBSIDIARIES.sql
@C:\proyectos\igtp5\DATA_TABLE\TRAILERS.sql
@C:\proyectos\igtp5\DATA_TABLE\TRANSFERS.sql
@C:\proyectos\igtp5\DATA_TABLE\TRUCKS.sql
@C:\proyectos\igtp5\DATA_TABLE\TYPE_CARGOS.sql
@C:\proyectos\igtp5\DATA_TABLE\TYPE_CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\DATA_TABLE\TYPE_DOCUMENTS.sql
@C:\proyectos\igtp5\DATA_TABLE\TYPE_FREIGHTS.sql
@C:\proyectos\igtp5\DATA_TABLE\TYPE_VEHICLES.sql
@C:\proyectos\igtp5\DATA_TABLE\UNITS_LOCATED.sql
@C:\proyectos\igtp5\DATA_TABLE\USERS.sql
@C:\proyectos\igtp5\INDEXES\FREIGHTS_UK_01.sql
@C:\proyectos\igtp5\INDEXES\SHOPS_PK.sql
@C:\proyectos\igtp5\INDEXES\CITIES_UK_01.sql
@C:\proyectos\igtp5\INDEXES\COUNTRIES_UK_02.sql
@C:\proyectos\igtp5\INDEXES\TRANSFER_UK_01.sql
@C:\proyectos\igtp5\INDEXES\EMPLOYEES_PK.sql
@C:\proyectos\igtp5\INDEXES\LOCATIONS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\LOCATIONS_UK_02.sql
@C:\proyectos\igtp5\INDEXES\CASHIERS_UK_02.sql
@C:\proyectos\igtp5\INDEXES\TYPE_DOCUMENTS.sql
@C:\proyectos\igtp5\INDEXES\TYPE_CARGOS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\ROUTES_PK.sql
@C:\proyectos\igtp5\INDEXES\ROUTE_LOCATIONS_PK.sql
@C:\proyectos\igtp5\INDEXES\COUNTRIES_UK_01.sql
@C:\proyectos\igtp5\INDEXES\TRUCKS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\SUBSIDIARIES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\USERS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\CUSTOMERS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\REGIONS_PK.sql
@C:\proyectos\igtp5\INDEXES\CUSTOMERS_PK.sql
@C:\proyectos\igtp5\INDEXES\TRUCKS_PK.sql
@C:\proyectos\igtp5\INDEXES\ROUTE_COSTS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\TRUCKS_UK_01.sql
@C:\proyectos\igtp5\INDEXES\COUNTRIES_PK.sql
@C:\proyectos\igtp5\INDEXES\LOCATIONS_PK.sql
@C:\proyectos\igtp5\INDEXES\PARTNERS_PK.sql
@C:\proyectos\igtp5\INDEXES\TRANSFERS_PK.sql
@C:\proyectos\igtp5\INDEXES\TYPE_VEHICLES_PK.sql
@C:\proyectos\igtp5\INDEXES\TRAILERS_UK_01.sql
@C:\proyectos\igtp5\INDEXES\SUBSIDIARIES_UK_01.sql
@C:\proyectos\igtp5\INDEXES\PROVINCES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\LOCATION_NEIGHBORS_PK.sql
@C:\proyectos\igtp5\INDEXES\CASHIERS_PK.sql
@C:\proyectos\igtp5\INDEXES\UNITS_LOCATED_PK.sql
@C:\proyectos\igtp5\INDEXES\SHOPS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\MUNICIPALITIES_PK.sql
@C:\proyectos\igtp5\INDEXES\TYPE_CARGOS_PK.sql
@C:\proyectos\igtp5\INDEXES\ROUTE_LOCATIONS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\CONFIGURATIONS_PK.sql
@C:\proyectos\igtp5\INDEXES\EMPLOYEES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\REGIONS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\CASHIERS_UK_01.sql
@C:\proyectos\igtp5\INDEXES\MUNICIPALITIES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\COUNTRIES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\CITIES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\LOCATIONS_UK_01.sql
@C:\proyectos\igtp5\INDEXES\TYPE_FREIGHTS_UK_01.sql
@C:\proyectos\igtp5\INDEXES\CASHIER_MOVEMENTS_PK.sql
@C:\proyectos\igtp5\INDEXES\TYPE_FREIGHTS_PK.sql
@C:\proyectos\igtp5\INDEXES\SUBSIDIARIES_PK.sql
@C:\proyectos\igtp5\INDEXES\ROUTE_COSTS.sql
@C:\proyectos\igtp5\INDEXES\TRAILERS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\CITIES_PK.sql
@C:\proyectos\igtp5\INDEXES\PROVINCES_PK.sql
@C:\proyectos\igtp5\INDEXES\USERS_PK.sql
@C:\proyectos\igtp5\INDEXES\FREIGHTS_PK.sql
@C:\proyectos\igtp5\INDEXES\TYPE_VEHICLES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\PARTNERS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\TYPE_DOCUMENTS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\CITIES_UK_02.sql
@C:\proyectos\igtp5\INDEXES\TYPE_CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\INDEXES\TRAILERS_PK.sql
@C:\proyectos\igtp5\INDEXES\ROUTES_UK_00.sql
@C:\proyectos\igtp5\INDEXES\TYPE_CASHIER_MOVEMENTS_UK_00.sql
@C:\proyectos\igtp5\INDEXES\LOCATION_NEIGHBORS_UK_00.sql
@C:\proyectos\igtp5\PROCEDURES\P_TEST.sql
@C:\proyectos\igtp5\PROCEDURES\XINSERTPARAMETER.sql
@C:\proyectos\igtp5\PACKAGES\CFG_API_K_CITY.sql
@C:\proyectos\igtp5\PACKAGES\CFG_API_K_LOCATION.sql
@C:\proyectos\igtp5\PACKAGES\CFG_API_K_MUNICIPALITY.sql
@C:\proyectos\igtp5\PACKAGES\CFG_API_K_PROVINCE.sql
@C:\proyectos\igtp5\PACKAGES\CFG_API_K_REGION.sql
@C:\proyectos\igtp5\PACKAGES\CFG_API_K_ROUTE_LOCATION.sql
@C:\proyectos\igtp5\PACKAGES\DSC_API_K_CUSTOMER.sql
@C:\proyectos\igtp5\PACKAGES\DSC_API_K_TRAILER.sql
@C:\proyectos\igtp5\PACKAGES\DSC_API_K_TRUCK.sql
@C:\proyectos\igtp5\PACKAGES\DSC_API_K_TYP_CARGO.sql
@C:\proyectos\igtp5\PACKAGES\DSC_API_K_TYPE_FREIGT.sql
@C:\proyectos\igtp5\PACKAGES\DSC_API_K_TYP_VEHICLE.sql
@C:\proyectos\igtp5\PACKAGES\LGC_API_K_FREIGHT.sql
@C:\proyectos\igtp5\PACKAGES\LGC_API_K_ROUTE.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_CSV_UTIL.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_DATE.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_DINAMIC.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_FILE_UTIL.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_GEO.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_GLOBAL.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_PDF_BUILDER.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_STRING_UTIL.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_UTILS.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_XLSX_BUILDER.sql
@C:\proyectos\igtp5\PACKAGES\SYS_K_ZIP_UTIL.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\CFG_API_K_CITY.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\CFG_API_K_LOCATION.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\CFG_API_K_MUNICIPALITY.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\CFG_API_K_PROVINCE.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\CFG_API_K_REGION.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\CFG_API_K_ROUTE_LOCATION.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\DSC_API_K_CUSTOMER.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\DSC_API_K_TRAILER.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\DSC_API_K_TRUCK.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\DSC_API_K_TYP_CARGO.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\DSC_API_K_TYPE_FREIGT.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\DSC_API_K_TYP_VEHICLE.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\LGC_API_K_FREIGHT.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\LGC_API_K_ROUTE.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_CSV_UTIL.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_DATE.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_DINAMIC.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_FILE_UTIL.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_GEO.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_GLOBAL.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_PDF_BUILDER.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_STRING_UTIL.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_UTILS.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_XLSX_BUILDER.sql
@C:\proyectos\igtp5\PACKAGE_BODIES\SYS_K_ZIP_UTIL.sql
@C:\proyectos\igtp5\FUNCTIONS\F_TEST.sql
@C:\proyectos\igtp5\CONSTRAINTS\CUSTOMERS.sql
@C:\proyectos\igtp5\CONSTRAINTS\TYPE_DOCUMENTS.sql
@C:\proyectos\igtp5\CONSTRAINTS\SHOPS.sql
@C:\proyectos\igtp5\CONSTRAINTS\LOCATIONS.sql
@C:\proyectos\igtp5\CONSTRAINTS\LOCATION_NEIGHBORS.sql
@C:\proyectos\igtp5\CONSTRAINTS\PROVINCES.sql
@C:\proyectos\igtp5\CONSTRAINTS\COUNTRIES.sql
@C:\proyectos\igtp5\CONSTRAINTS\PARTNERS.sql
@C:\proyectos\igtp5\CONSTRAINTS\TYPE_CARGOS.sql
@C:\proyectos\igtp5\CONSTRAINTS\CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\CONSTRAINTS\ROUTE_LOCATIONS.sql
@C:\proyectos\igtp5\CONSTRAINTS\SUBSIDIARIES.sql
@C:\proyectos\igtp5\CONSTRAINTS\TRAILERS.sql
@C:\proyectos\igtp5\CONSTRAINTS\TRANSFERS.sql
@C:\proyectos\igtp5\CONSTRAINTS\CASHIERS.sql
@C:\proyectos\igtp5\CONSTRAINTS\TRUCKS.sql
@C:\proyectos\igtp5\CONSTRAINTS\TYPE_VEHICLES.sql
@C:\proyectos\igtp5\CONSTRAINTS\USERS.sql
@C:\proyectos\igtp5\CONSTRAINTS\CITIES.sql
@C:\proyectos\igtp5\CONSTRAINTS\FREIGHTS.sql
@C:\proyectos\igtp5\CONSTRAINTS\MUNICIPALITIES.sql
@C:\proyectos\igtp5\CONSTRAINTS\REGIONS.sql
@C:\proyectos\igtp5\CONSTRAINTS\ROUTE_COSTS.sql
@C:\proyectos\igtp5\CONSTRAINTS\EMPLOYEES.sql
@C:\proyectos\igtp5\CONSTRAINTS\ROUTES.sql
@C:\proyectos\igtp5\CONSTRAINTS\TYPE_CASHIER_MOVEMENTS.sql
@C:\proyectos\igtp5\CONSTRAINTS\TYPE_FREIGHTS.sql
@C:\proyectos\igtp5\CONSTRAINTS\UNITS_LOCATED.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\CITIES.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\CUSTOMERS.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\LOCATION_NEIGHBORS.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\LOCATIONS.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\MUNICIPALITIES.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\PROVINCES.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\REGIONS.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\ROUTE_LOCATIONS.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\ROUTES.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\SHOPS.sql
@C:\proyectos\igtp5\REF_CONSTRAINTS\SUBSIDIARIES.sql
